name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: build package
      run: make dist

    - name: publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
              user: __token__
              password: ${{ secrets.PYPI_API_TOKEN }}
